/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conway;
import java.awt.Graphics;

/**
 *
 * @author alan
 */
public class LifePanel extends javax.swing.JPanel {

    Life myLife = new Life();
    
    private final LifeFrame theFrame;
    private boolean running = true;
    
    /**
     * Creates new form LifePanel
     */
    public LifePanel(LifeFrame f) {
        initComponents();
        theFrame = f;
    }
    
    public void paintComponent(Graphics g) {
        g.fillRect(100, 100, 20, 20);
        myLife.paint(g);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Step = new javax.swing.JButton();

        setLayout(null);

        Step.setText("Step");
        Step.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StepActionPerformed(evt);
            }
        });
        add(Step);
        Step.setBounds(290, 40, 67, 25);
    }// </editor-fold>//GEN-END:initComponents

    private void StepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StepActionPerformed
        
    }//GEN-LAST:event_StepActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Step;
    // End of variables declaration//GEN-END:variables
}
